# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20160411_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[(b'1', b'Standard'), (b'2', b'VIP')], default=1, max_length=50),
        ),
    ]
